DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS zones;
DROP TABLE IF EXISTS transport;

CREATE TABLE zones (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1 ) PRIMARY KEY,
  latitude  DOUBLE  NOT NULL,
  longitude DOUBLE  NOT NULL,
  radius    INTEGER NOT NULL
);

CREATE TABLE transport (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1 ) PRIMARY KEY,
  latitude  DOUBLE NOT NULL,
  longitude DOUBLE NOT NULL
);

CREATE TABLE events (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1 ) PRIMARY KEY,
  date         TIMESTAMP DEFAULT now() NOT NULL,
  type         VARCHAR(5)              NOT NULL,
  zone_id      INTEGER                 NOT NULL,
  transport_id INTEGER                 NOT NULL,
  FOREIGN KEY (zone_id) REFERENCES zones (id),
  FOREIGN KEY (transport_id) REFERENCES transport (id)
);
